name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    strategy:
      matrix:
        runs-on: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        version: v0.13.1
    - run: |
        wasm-pack --version
